CONNECTION_URL=jdbc:mariadb://localhost:3306/taxi

LOGIN_USER=login
LOGIN_PASS=login

REGISTRAZIONE_USER=registrazione
REGISTRAZIONE_PASS=registrazione

CLIENTE_USER=cliente
CLIENTE_PASS=cliente

TASSISTA_USER=tassista
TASSISTA_PASS=tassista

GESTORE_USER=gestore
GESTORE_PASS=gestore
